version: "3"

services: 
    db:
        build: ./docker/db
        ports: 
            - 27017:27017
        volumes: 
            - /data/db
        environment: 
            MONGO_INITDB_DATABASE: bbs
            MONGO_INITDB_ROOT_USERNAME: springboot
            MONGO_INITDB_ROOT_PASSWORD: springboot
    
    express:
        build: ./docker/express
        ports:
            - 9001:8081
        environment: 
            ME_CONFIG_MONGODB_SERVER: db
            ME_CONFIG_MONGODB_ADMINUSERNAME: springboot
            ME_CONFIG_MONGODB_ADMINPASSWORD: springboot
            ME_CONFIG_MONGODB_PORT: 27017
