# SERVER_PORT
server:
  port: 9000

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: bbs
      username: springboot
      password: springboot

  thymeleaf:
    cache: false
    encoding: UTF-8
    
logging:
  level:
    jp.mirageworld: DEBUG